2025-07-21 21:13:32,201:ERROR:{'message': ZeroDivisionError('division by zero'), 'detail': 'Traceback (most recent call last):\n  File "/Users/fersoriano/Documents/programming/bootcamp-backend-python/python_exceptions/logs/create_file_errors.py", line 11, in <module>\n    a = 10 / 0\n        ~~~^~~\nZeroDivisionError: division by zero\n'}
2025-07-21 21:13:32,202:CRITICAL:{'message': Exception('Se perdio la conexion a la Base de Datos'), 'detail': 'Traceback (most recent call last):\n  File "/Users/fersoriano/Documents/programming/bootcamp-backend-python/python_exceptions/logs/create_file_errors.py", line 20, in <module>\n    raise Exception("Se perdio la conexion a la Base de Datos")\nException: Se perdio la conexion a la Base de Datos\n'}
2025-07-21 21:14:10,288:ERROR:{'message': 'division by zero', 'detail': 'Traceback (most recent call last):\n  File "/Users/fersoriano/Documents/programming/bootcamp-backend-python/python_exceptions/logs/create_file_errors.py", line 11, in <module>\n    a = 10 / 0\n        ~~~^~~\nZeroDivisionError: division by zero\n'}
2025-07-21 21:14:10,289:CRITICAL:{'message': 'Se perdio la conexion a la Base de Datos', 'detail': 'Traceback (most recent call last):\n  File "/Users/fersoriano/Documents/programming/bootcamp-backend-python/python_exceptions/logs/create_file_errors.py", line 20, in <module>\n    raise Exception("Se perdio la conexion a la Base de Datos")\nException: Se perdio la conexion a la Base de Datos\n'}
2025-07-21 21:14:38,291:CRITICAL:{'message': 'Se perdio la conexion a la Base de Datos', 'detail': 'Traceback (most recent call last):\n  File "/Users/fersoriano/Documents/programming/bootcamp-backend-python/python_exceptions/logs/create_file_errors.py", line 20, in <module>\n    raise Exception("Se perdio la conexion a la Base de Datos")\nException: Se perdio la conexion a la Base de Datos\n'}
2025-07-21 22:17:09,481:CRITICAL:{'message': 'Se perdio la conexion a la Base de Datos', 'detail': 'Traceback (most recent call last):\n  File "/Users/fersoriano/Documents/programming/bootcamp-backend-python/python_exceptions/logs/create_file_errors.py", line 30, in <module>\n    raise Exception("Se perdio la conexion a la Base de Datos")\nException: Se perdio la conexion a la Base de Datos\n'}
